#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAPI.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyAPI")]
	public partial class QuanLyAPIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblHang(tblHang instance);
    partial void UpdatetblHang(tblHang instance);
    partial void DeletetblHang(tblHang instance);
    #endregion
		
		public QuanLyAPIDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyAPIConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyAPIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyAPIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyAPIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyAPIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblHang> tblHangs
		{
			get
			{
				return this.GetTable<tblHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHang")]
	public partial class tblHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHang;
		
		private string _TenHang;
		
		private string _HoatChatHamLuong;
		
		private string _DangBaoChe;
		
		private string _QuyCachDongGoi;
		
		private string _HanSuDung;
		
		private string _CongTySanXuat;
		
		private string _CongTyDangKy;
		
		private string _GiaKeKhai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnHoatChatHamLuongChanging(string value);
    partial void OnHoatChatHamLuongChanged();
    partial void OnDangBaoCheChanging(string value);
    partial void OnDangBaoCheChanged();
    partial void OnQuyCachDongGoiChanging(string value);
    partial void OnQuyCachDongGoiChanged();
    partial void OnHanSuDungChanging(string value);
    partial void OnHanSuDungChanged();
    partial void OnCongTySanXuatChanging(string value);
    partial void OnCongTySanXuatChanged();
    partial void OnCongTyDangKyChanging(string value);
    partial void OnCongTyDangKyChanged();
    partial void OnGiaKeKhaiChanging(string value);
    partial void OnGiaKeKhaiChanged();
    #endregion
		
		public tblHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatChatHamLuong", DbType="NVarChar(MAX)")]
		public string HoatChatHamLuong
		{
			get
			{
				return this._HoatChatHamLuong;
			}
			set
			{
				if ((this._HoatChatHamLuong != value))
				{
					this.OnHoatChatHamLuongChanging(value);
					this.SendPropertyChanging();
					this._HoatChatHamLuong = value;
					this.SendPropertyChanged("HoatChatHamLuong");
					this.OnHoatChatHamLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangBaoChe", DbType="NVarChar(50)")]
		public string DangBaoChe
		{
			get
			{
				return this._DangBaoChe;
			}
			set
			{
				if ((this._DangBaoChe != value))
				{
					this.OnDangBaoCheChanging(value);
					this.SendPropertyChanging();
					this._DangBaoChe = value;
					this.SendPropertyChanged("DangBaoChe");
					this.OnDangBaoCheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyCachDongGoi", DbType="NVarChar(MAX)")]
		public string QuyCachDongGoi
		{
			get
			{
				return this._QuyCachDongGoi;
			}
			set
			{
				if ((this._QuyCachDongGoi != value))
				{
					this.OnQuyCachDongGoiChanging(value);
					this.SendPropertyChanging();
					this._QuyCachDongGoi = value;
					this.SendPropertyChanged("QuyCachDongGoi");
					this.OnQuyCachDongGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanSuDung", DbType="NVarChar(20)")]
		public string HanSuDung
		{
			get
			{
				return this._HanSuDung;
			}
			set
			{
				if ((this._HanSuDung != value))
				{
					this.OnHanSuDungChanging(value);
					this.SendPropertyChanging();
					this._HanSuDung = value;
					this.SendPropertyChanged("HanSuDung");
					this.OnHanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTySanXuat", DbType="NVarChar(MAX)")]
		public string CongTySanXuat
		{
			get
			{
				return this._CongTySanXuat;
			}
			set
			{
				if ((this._CongTySanXuat != value))
				{
					this.OnCongTySanXuatChanging(value);
					this.SendPropertyChanging();
					this._CongTySanXuat = value;
					this.SendPropertyChanged("CongTySanXuat");
					this.OnCongTySanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTyDangKy", DbType="NVarChar(MAX)")]
		public string CongTyDangKy
		{
			get
			{
				return this._CongTyDangKy;
			}
			set
			{
				if ((this._CongTyDangKy != value))
				{
					this.OnCongTyDangKyChanging(value);
					this.SendPropertyChanging();
					this._CongTyDangKy = value;
					this.SendPropertyChanged("CongTyDangKy");
					this.OnCongTyDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaKeKhai", DbType="NVarChar(50)")]
		public string GiaKeKhai
		{
			get
			{
				return this._GiaKeKhai;
			}
			set
			{
				if ((this._GiaKeKhai != value))
				{
					this.OnGiaKeKhaiChanging(value);
					this.SendPropertyChanging();
					this._GiaKeKhai = value;
					this.SendPropertyChanged("GiaKeKhai");
					this.OnGiaKeKhaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
